[project]
name = "github-page"
version = "0.0.0"
edition = "0.1.0"

[todo]
name = "structure projects better"
difficulty = 0.4
priority = 0.1

[todo]
name = "make it prettier"
difficulty = 0.8
priority = 0.6

[[todo.todo]]
name = "display projects better"
difficulty = 0.5
priority = 0.6

[done]
name = "make quick prototype"
difficulty = 0.3
priority = 0.9
